version: '3.8'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: terrain
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3316:3306"
    volumes:
      - ./db:/var/lib/mysql
